apiVersion: v1
kind: Secret
metadata:
    namespace: frontend-namespace
    name: frontend-secret
data:
    #ENC[AES256_GCM,data:/KF4XJpsQEgpPYFpXB95WD+Y2IB0U8K37PE=,iv:A23/GzYY04iEXTE4XpXP8OoMzoUe2YdozXNr7vIRQC0=,tag:kKsTsVAHq0BTMasxhiOkYQ==,type:comment]
    PGDB_USER: ENC[AES256_GCM,data:K3N3fyKO+7PjkXcftCVysYFUJUA=,iv:xOoatzRvSYfTxJbMPsNPXaRYOR24+Vw/Nox2FZHJSnE=,tag:gvvrueEEMnRozW/f87mBWQ==,type:str]
    #ENC[AES256_GCM,data:ZKbIuKlwHQqa9d+VEnLOzWTiWBv6C/shf0w=,iv:EJjYO8FPHqJK2Ju9wz7GVzRFXqlBFqm+69YqzpwCBho=,tag:aN2C5fdD4GPXAFmR3oHeMg==,type:comment]
    PGDB_PASSWORD: ENC[AES256_GCM,data:+HXJwPLMQVcoyjXHkf7iLA==,iv:XOrF+EDhYm9G818u67a5qxhFFO3wVT8muZablfw5JUs=,tag:Dtl8Zeai7BjagMQNa2VTRg==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/tokyo-ceiling-435523-d0/locations/northamerica-northeast1/keyRings/my-keyring/cryptoKeys/key-one
          created_at: "2024-12-11T01:26:37Z"
          enc: CiQA47xFFXGuUZXOzMvpQdX+ZYdfXC3BC9P6inpZXjh38+t2RVoSSQBZv+7jypSA9FF+H3dLx7vG8yJtlOTUZ0c4ruwVCwqpduOlAbRinSrta3SD4elLj6M7UHC5BWwkxhBe5JgJLlHckXe+EFetwuw=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-12-11T01:26:37Z"
    mac: ENC[AES256_GCM,data:188gkKnHVI8fuOz5NH8yNhPZaflOQBV/0M6yWmLLknvHb2pBvBFnylOKoX4APIjWHOiGO4G+TcWG11OkD6tOhdhIhlyaPy2mIn/lXvgutNWKM/cjC72ixa6PMU6YCqnSS0KhR3XNwfYojZSEdFxdmf57PGgN1IigGAqysKrfJqc=,iv:GnBpjMjBQIedT7mydJG0RvNnfH3OJVwgsqF2cX10usM=,tag:EAVCcE/t69FdUxAEg0K7bQ==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.7.1
