apiVersion: v1
kind: Secret
metadata:
    namespace: postgres-database
    name: postgres-secret
data:
    #ENC[AES256_GCM,data:mM0XEYVyF+rUC6g=,iv:23n267pnHsQg+iDocJ9VLyefGUNkTQRPVHxHdGrn4Xg=,tag:Uo9lgzy08ZpWVWsX4ZbA0w==,type:comment]
    POSTGRES_USER: ENC[AES256_GCM,data:n3UXFzkRhMIaoURE,iv:QjrcbUhkiRRsF6XPoL8ujAWdYB9isxAoIqmuVDgcRwU=,tag:daUfc9im99cGzkVkD0s8uw==,type:str]
    #ENC[AES256_GCM,data:zxHiZGyXsy1lFQ==,iv:NktBp2fyZX/HiegYX2QpVMnA6fOSvnP6wVu0+ccwL6I=,tag:OsjqDrokCD16XnwkQIkmbw==,type:comment]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:0pZFtwpn6DXAaVLD,iv:yLBPXf7ID15w1QRvOKAUHZHFy9Xr4+AtkVPdDSc6xzw=,tag:gABkuuJ/E667Hp0Dxh2isA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/tokyo-ceiling-435523-d0/locations/northamerica-northeast1/keyRings/my-keyring/cryptoKeys/key-one
          created_at: "2024-12-11T01:23:34Z"
          enc: CiQA47xFFSyIVYubrvAKywDNT+xpH4v79DU4RwPSCb/bhejsGoYSSQBZv+7jzyZ2VK03GxIDWxRk6HT8RDWSw29Nwg96IBTbmgO2xp7IQxHukxronLtFz3sxOT7ZDEBkAJVDcfPiJ36ZoQyePtej8OQ=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-12-11T01:23:35Z"
    mac: ENC[AES256_GCM,data:KX8Prveuu93BsmPax6PWd1nwWWCRrwFv3AJvkUBvb4BHXzQBQjpTIpvUS/nYbRmnlVN8XFFrjRUEF3FYGZas6GchcFxo2gfmZyzRPPo/wphUDwge2O9Z8GgEusKdNFIRjo1VICdLIzkiymo0Jp9/dsmVRXzNcNYSf5OCZrddnpw=,iv:bDThFnM0qmIqGPGgtMaszSWpJpy5RvF+a06cIQiDsCY=,tag:wTmyNkw9xkk902aAbBcovw==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.7.1
