apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: postgres-database
spec:
  selector:
    app: postgres-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
